/**
 * Script Generator v2 - Uses Groq LLM to generate restaurant ad scripts
 *
 * POC Focus: Optimized for three demo restaurants with rich brand context:
 * - Joe's Pizza (NYC iconic pizza since 1975)
 * - Sweetgreen (healthy salads/bowls, farm-to-table)
 * - Doughnut Vault (Chicago artisan donuts)
 *
 * Key Changes in v2:
 * - Removed stock_video - all visuals use animated_image via Akool
 * - Rich POC brand context for better LLM output
 * - Image diversity selection by category
 * - Akool animation prompts generated by LLM
 */

import Groq from 'groq-sdk';
import { generatePOCScriptPrompt, generateGenericScriptPrompt } from './prompts';
import { detectPOCBrand, POC_BRANDS } from './poc-brands';
import type { POCBrandConfig } from './poc-brands';
import type {
  AdTone,
  ScriptGeneratorInput,
  GeneratedScript,
  ScriptGeneratorResult,
  AdScene,
  ContactInfo,
  VisualType,
  LLMSceneOutput,
  AkoolAnimationConfig,
} from './types';

// Re-export types and utilities
export type {
  AdTone,
  ScriptGeneratorInput,
  GeneratedScript,
  ScriptGeneratorResult,
  AdScene,
  ContactInfo,
  VisualType,
  AkoolAnimationConfig,
};
export { detectPOCBrand, POC_BRANDS };
export type { POCBrandConfig };

// Re-export image selector
export {
  selectImagesForAd,
  categorizeImages,
  getImageCategorySummary,
  selectImagesForScenePlan,
  getMainDishType,
  detectFoodType,
} from './image-selector';
export type {
  CategorizedImage,
  CategorizedImages,
  MainDishType,
  SelectedImageWithMode,
} from './image-selector';

// Re-export akool prompt generator
export {
  generateAkoolPrompt,
  generateAkoolPromptsForScenes,
  generatePOCAkoolPrompt,
  generateAkoolPromptWithLLM,
  generateAkoolPromptsWithLLM,
  DEFAULT_AKOOL_CONFIG,
  NEGATIVE_PROMPT,
} from './akool-prompts';

// Re-export scene planner
export {
  planScenes,
  selectRandomPattern,
  getAnimatedSceneIndices,
  getStaticSceneIndices,
  isAnimatedScene,
  getSceneKenBurnsDirection,
  prioritizeMainDishForAnimation,
  BODY_SCENE_PATTERNS,
} from './scene-planner';
export type {
  SceneVisualMode,
  BodyScenePattern,
  PlannedScene,
  ScenePlan,
} from './scene-planner';

/**
 * Compute fullScript by concatenating all scene voiceovers
 */
function computeFullScript(scenes: AdScene[]): string {
  return scenes.map(s => s.voiceoverText).join(' ');
}

/**
 * Extract display-friendly website from URL
 */
function extractDisplayWebsite(url?: string): string | undefined {
  if (!url) return undefined;
  try {
    const parsed = new URL(url);
    return parsed.hostname.replace(/^www\./, '');
  } catch {
    return undefined;
  }
}

/**
 * Initialize Groq client
 */
function getGroqClient(): Groq {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error('GROQ_API_KEY environment variable is not set');
  }
  return new Groq({ apiKey });
}

/**
 * Default Akool animation config
 */
const DEFAULT_AKOOL_CONFIG: AkoolAnimationConfig = {
  prompt: 'slow zoom in, gentle motion, appetizing food photography',
  negativePrompt: 'blurry, distorted, oversaturated, cartoon, illustration',
  videoLength: 5,
  resolution: '720p',
};

/**
 * Parse and validate LLM response for v2 format
 */
function parseScriptResponse(
  response: string,
  expectedTone: AdTone,
  expectedDuration: number,
  contactInfo?: ContactInfo
): GeneratedScript | null {
  try {
    // Clean up response - remove markdown code blocks if present
    let cleaned = response.trim();
    if (cleaned.startsWith('```json')) {
      cleaned = cleaned.slice(7);
    } else if (cleaned.startsWith('```')) {
      cleaned = cleaned.slice(3);
    }
    if (cleaned.endsWith('```')) {
      cleaned = cleaned.slice(0, -3);
    }
    cleaned = cleaned.trim();

    const parsed = JSON.parse(cleaned);

    // Validate required fields
    if (!Array.isArray(parsed.scenes) || parsed.scenes.length < 4) {
      console.error('Invalid script structure - expected 4+ scenes:', parsed);
      return null;
    }

    // Valid visual types
    const validVisualTypes: VisualType[] = ['animated_image', 'logo_brand'];

    // Valid scene IDs - includes new body1-4 format and legacy value/benefit/extra
    const validSceneIds = ['hook', 'body1', 'body2', 'body3', 'body4', 'value', 'benefit', 'extra', 'cta'];
    for (const scene of parsed.scenes) {
      if (!scene.id || !scene.voiceoverText || !scene.displayText || typeof scene.duration !== 'number') {
        console.error('Invalid scene structure:', scene);
        return null;
      }
      if (!validSceneIds.includes(scene.id)) {
        console.error('Invalid scene id:', scene.id);
        return null;
      }
    }

    // Build scenes - NOTE: visualType and akoolConfig will be set by scene planner
    // This parsing step just extracts the LLM's creative output
    const scenes: AdScene[] = parsed.scenes.map((s: LLMSceneOutput) => {
      // Determine visual type:
      // - CTA always gets logo_brand
      // - Hook gets animated_image (but scene planner will mark it as static/Ken Burns)
      // - Body scenes get animated_image (scene planner decides which are truly animated)
      let visualType: VisualType;
      if (s.visualType && validVisualTypes.includes(s.visualType)) {
        visualType = s.visualType;
      } else {
        visualType = s.id === 'cta' ? 'logo_brand' : 'animated_image';
      }

      const scene: AdScene = {
        id: s.id as AdScene['id'],
        voiceoverText: String(s.voiceoverText),
        displayText: String(s.displayText),
        duration: Number(s.duration),
        visualType,
        visualCategory: s.visualCategory || undefined,
      };

      // NOTE: We do NOT add akoolConfig here anymore
      // The scene planner determines which scenes are animated vs static
      // akoolConfig should only be added to truly animated scenes (visualMode === 'animated')
      // This is handled in the test script / API route after scene planning

      // Add contact overlay to CTA scene
      if (scene.id === 'cta' && contactInfo) {
        scene.contactOverlay = contactInfo;
      }

      return scene;
    });

    const script: GeneratedScript = {
      fullScript: computeFullScript(scenes),
      scenes,
      tone: (parsed.tone as AdTone) || expectedTone,
      totalDuration: Number(parsed.totalDuration) || expectedDuration,
    };

    return script;
  } catch (error) {
    console.error('Failed to parse script response:', error);
    return null;
  }
}

/**
 * Generate fallback script for POC brands
 */
function generatePOCFallback(
  brand: POCBrandConfig,
  duration: number,
  contactInfo?: ContactInfo
): GeneratedScript {
  const sceneCount = duration <= 15 ? 4 : 5;
  const sceneDuration = Math.round(duration / sceneCount);
  const categories = Object.keys(brand.menuCategories);

  const scenes: AdScene[] = [
    {
      id: 'hook',
      voiceoverText: `Discover ${brand.brandName}, ${brand.uniqueQualities[0].toLowerCase()}.`,
      displayText: 'DISCOVER',
      duration: sceneDuration,
      visualType: 'animated_image',
      visualCategory: categories[0],
      akoolConfig: {
        prompt: 'slow zoom in, warm lighting, appetizing close-up',
        negativePrompt: 'blurry, distorted, oversaturated',
        videoLength: 5,
        resolution: '720p',
      },
    },
    {
      id: 'value',
      voiceoverText: brand.uniqueQualities[1] || 'Quality ingredients, made fresh daily.',
      displayText: 'QUALITY',
      duration: sceneDuration,
      visualType: 'animated_image',
      visualCategory: categories[1] || categories[0],
      akoolConfig: {
        prompt: 'gentle camera movement, fresh ingredients visible',
        negativePrompt: 'blurry, distorted, oversaturated',
        videoLength: 5,
        resolution: '720p',
      },
    },
    {
      id: 'benefit',
      voiceoverText: 'Taste the difference that quality makes.',
      displayText: 'TASTE',
      duration: sceneDuration,
      visualType: 'animated_image',
      visualCategory: categories[2] || categories[0],
      akoolConfig: {
        prompt: 'smooth zoom, natural light, inviting atmosphere',
        negativePrompt: 'blurry, distorted, oversaturated',
        videoLength: 5,
        resolution: '720p',
      },
    },
    {
      id: 'cta',
      voiceoverText: `Visit ${brand.brandName} today.`,
      displayText: 'ORDER NOW',
      duration: sceneDuration,
      visualType: 'logo_brand',
      contactOverlay: contactInfo,
    },
  ];

  // Add extra scene for longer ads
  if (sceneCount === 5) {
    scenes.splice(3, 0, {
      id: 'benefit', // Second benefit
      voiceoverText: brand.uniqueQualities[2] || 'An experience worth coming back for.',
      displayText: 'EXPERIENCE',
      duration: sceneDuration,
      visualType: 'animated_image',
      visualCategory: categories[3] || categories[1] || categories[0],
      akoolConfig: {
        prompt: 'gentle pan, cozy atmosphere, inviting scene',
        negativePrompt: 'blurry, distorted, oversaturated',
        videoLength: 5,
        resolution: '720p',
      },
    });
  }

  return {
    fullScript: computeFullScript(scenes),
    scenes,
    tone: brand.tone,
    totalDuration: duration,
  };
}

/**
 * Generate fallback script for non-POC brands
 */
function generateGenericFallback(
  brandName: string,
  tone: AdTone,
  duration: number,
  contactInfo?: ContactInfo
): GeneratedScript {
  const sceneDuration = Math.round(duration / 4);

  const scenes: AdScene[] = [
    {
      id: 'hook',
      voiceoverText: `Discover what makes ${brandName} special.`,
      displayText: 'DISCOVER',
      duration: sceneDuration,
      visualType: 'animated_image',
      visualCategory: 'main',
      akoolConfig: DEFAULT_AKOOL_CONFIG,
    },
    {
      id: 'value',
      voiceoverText: 'Quality ingredients, prepared fresh daily.',
      displayText: 'FRESH DAILY',
      duration: sceneDuration,
      visualType: 'animated_image',
      visualCategory: 'main',
      akoolConfig: DEFAULT_AKOOL_CONFIG,
    },
    {
      id: 'benefit',
      voiceoverText: 'Taste the difference quality makes.',
      displayText: 'TASTE',
      duration: sceneDuration,
      visualType: 'animated_image',
      visualCategory: 'main',
      akoolConfig: DEFAULT_AKOOL_CONFIG,
    },
    {
      id: 'cta',
      voiceoverText: 'Visit us today.',
      displayText: 'ORDER NOW',
      duration: sceneDuration,
      visualType: 'logo_brand',
      contactOverlay: contactInfo,
    },
  ];

  return {
    fullScript: computeFullScript(scenes),
    scenes,
    tone,
    totalDuration: duration,
  };
}

/**
 * Generate an ad script using Groq LLM
 * Enhanced with POC brand detection for better results
 */
export async function generateScript(input: ScriptGeneratorInput): Promise<ScriptGeneratorResult> {
  const {
    brandName,
    tagline,
    description,
    cuisine,
    tone = 'friendly',
    duration = 20, // Default to 20s for richer ads
    url,
    contact,
  } = input;

  if (!brandName || brandName.trim().length === 0) {
    return {
      success: false,
      error: 'Brand name is required',
    };
  }

  // Detect POC brand
  const pocBrand = detectPOCBrand(brandName, url);
  if (pocBrand) {
    console.log(`POC Brand detected: ${pocBrand.brandName}`);
  }

  // Determine effective tone
  const effectiveTone = tone || pocBrand?.tone || 'friendly';

  // Build contact info for CTA scene
  const contactInfo: ContactInfo | undefined = contact || (url ? {
    website: extractDisplayWebsite(url),
  } : undefined);

  try {
    const groq = getGroqClient();

    // Generate appropriate prompt
    // Pass USP (tagline) to POC prompt for hook scene
    const prompt = pocBrand
      ? generatePOCScriptPrompt(pocBrand, duration, tagline)
      : generateGenericScriptPrompt(brandName, tagline, description, cuisine, effectiveTone, duration);

    const completion = await groq.chat.completions.create({
      model: 'llama-3.1-8b-instant', // Fast and free
      messages: [
        {
          role: 'system',
          content: 'You are an expert advertising copywriter specializing in restaurant commercials. You create compelling, professional ad scripts. Output only valid JSON, no explanations or markdown.',
        },
        {
          role: 'user',
          content: prompt,
        },
      ],
      temperature: 0.7,
      max_tokens: 800, // Increased for richer output
      response_format: { type: 'json_object' },
    });

    const responseText = completion.choices[0]?.message?.content;
    if (!responseText) {
      throw new Error('Empty response from Groq');
    }

    const script = parseScriptResponse(responseText, effectiveTone, duration, contactInfo);
    if (!script) {
      // Use fallback if parsing fails
      console.warn('Using fallback script due to parsing failure');
      const fallback = pocBrand
        ? generatePOCFallback(pocBrand, duration, contactInfo)
        : generateGenericFallback(brandName, effectiveTone, duration, contactInfo);

      return {
        success: true,
        script: fallback,
        pocBrand: pocBrand?.brandName,
      };
    }

    return {
      success: true,
      script,
      pocBrand: pocBrand?.brandName,
    };
  } catch (error) {
    console.error('Script generation error:', error);

    // Check for specific error types
    if (error instanceof Error) {
      if (error.message.includes('GROQ_API_KEY')) {
        return {
          success: false,
          error: 'Groq API key not configured. Please set GROQ_API_KEY in environment variables.',
        };
      }
    }

    // Use fallback for any error
    console.warn('Using fallback script due to error:', error);
    const fallback = pocBrand
      ? generatePOCFallback(pocBrand, duration, contactInfo)
      : generateGenericFallback(brandName, effectiveTone, duration, contactInfo);

    return {
      success: true,
      script: fallback,
      pocBrand: pocBrand?.brandName,
    };
  }
}

/**
 * Generate script from scraped data
 * Convenience function that extracts relevant fields from scraper output
 */
export async function generateScriptFromScrapedData(
  scrapedData: {
    brand?: {
      name?: string;
      tagline?: string;
      description?: string;
      cuisine?: string;
    };
    sourceUrl?: string;
    contact?: {
      phone?: string;
      address?: string;
      hours?: string;
      website?: string;
    };
  },
  tone?: AdTone,
  duration: number = 20
): Promise<ScriptGeneratorResult> {
  const brandName = scrapedData.brand?.name || 'Restaurant';
  const tagline = scrapedData.brand?.tagline;
  const description = scrapedData.brand?.description;
  const cuisine = scrapedData.brand?.cuisine;
  const url = scrapedData.sourceUrl;

  // Build contact info from scraped data
  const contact: ContactInfo | undefined = scrapedData.contact ? {
    phone: scrapedData.contact.phone,
    address: scrapedData.contact.address,
    hours: scrapedData.contact.hours,
    website: scrapedData.contact.website || extractDisplayWebsite(url),
  } : (url ? { website: extractDisplayWebsite(url) } : undefined);

  return generateScript({
    brandName,
    tagline,
    description,
    cuisine,
    tone,
    duration,
    url,
    contact,
  });
}
